# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20161221_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarToken', models.CharField(max_length=20)),
                ('avatarSource', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('responsibility', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('parentClass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('loginTime', models.CharField(max_length=30)),
                ('loginIp', models.CharField(max_length=20)),
                ('loginAddress', models.CharField(max_length=20)),
                ('integral', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('avatarToken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Avatar')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Project')),
                ('skillTree', models.ManyToManyField(to='TestModel.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('jobDescription', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publish_time',
            new_name='publishTime',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.User'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='TestModel.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='workExperience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.WorkExperience'),
        ),
    ]
