# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20161223_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publishTime', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('describe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('loginTime', models.CharField(max_length=30)),
                ('loginIp', models.CharField(max_length=20)),
                ('loginAddress', models.CharField(max_length=20)),
                ('integral', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('avatarToken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Avatar')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Project')),
                ('skillTree', models.ManyToManyField(to='TestModel.Skill')),
                ('workExperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.WorkExperience')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='TestModel.Category'),
        ),
    ]
